// <auto-generated />
using GrpcServiceDataBase.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GrpcServiceDataBase.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20231118232500_new_init")]
    partial class new_init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GrpcServiceDataBase.Model.DAL.Entities.ClientBankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account");

                    b.Property<int>("ClientInfoId")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.HasKey("Id");

                    b.HasIndex("ClientInfoId");

                    b.ToTable("ClientBankAccounts");
                });

            modelBuilder.Entity("GrpcServiceDataBase.Model.DAL.Entities.ClientInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastName");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("ClientInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Тестов",
                            LastName = "Тестович",
                            Name = "Тест",
                            Password = "12345",
                            Phone = "89969520206"
                        });
                });

            modelBuilder.Entity("GrpcServiceDataBase.Model.DAL.Entities.ClientBankAccount", b =>
                {
                    b.HasOne("GrpcServiceDataBase.Model.DAL.Entities.ClientInfo", "ClientInfo")
                        .WithMany("ClientBankAccounts")
                        .HasForeignKey("ClientInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ClientId");

                    b.Navigation("ClientInfo");
                });

            modelBuilder.Entity("GrpcServiceDataBase.Model.DAL.Entities.ClientInfo", b =>
                {
                    b.Navigation("ClientBankAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
